let lookupPronunciations={};
let lookupVoices=[];
const $=id=>document.getElementById(id);
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function findKey(obj,k){return Object.keys(obj||{}).find(x=>x.toLowerCase()===k)||null;}
function canonicalWord(q){const k=q.toLowerCase();return allWords().find(w=>w.toLowerCase()===k)||null;}
function removedWord(q){const k=q.toLowerCase();return Object.keys(state.removedWords||{}).find(w=>w.toLowerCase()===k)||null;}
function pronunciationHtml(w){const k=w.toLowerCase(),p=(state.customPronunciations&&state.customPronunciations[k])||lookupPronunciations[k];if(!p)return "";const a=[];if(p.uk)a.push('<span class="ipaChip ipaUk" title="UK" dir="ltr" lang="en">'+esc(p.uk)+'</span>');if(p.us)a.push('<span class="ipaChip ipaUs" title="US" dir="ltr" lang="en">'+esc(p.us)+'</span>');if(!a.length&&p.fallback)a.push('<span class="ipaChip ipaGeneric" title="IPA" dir="ltr" lang="en">'+esc(p.fallback)+'</span>');return a.length?'<div class="ipaLine">'+a.join('')+'</div>':"";}
async function loadPron(){try{const r=await fetch("data/pronunciations.json?v=3.28",{cache:"no-cache"});const j=await r.json();lookupPronunciations=j?.words||{};}catch(e){} const q=new URLSearchParams(location.search).get("word");if(q)runLookup(q);}
function preferredVoices(){const all=speechSynthesis.getVoices(),en=all.filter(v=>/^en([-_]|$)/i.test(v.lang||""));const novelty=/(bells?|boing|bubbles?|cellos?|good news|bad news|whisper|wobble|zarvox|trinoids?|organ|superstar|jester|bahh|deranged|hysterical|robot|novelty)/i;const p=en.filter(v=>!novelty.test(v.name||""));return p.length>=2?p:(en.length?en:all);}
function refreshVoices(){lookupVoices=preferredVoices();}
speechSynthesis.onvoiceschanged=refreshVoices;refreshVoices();
function speak(w){try{if("audioSession" in navigator&&navigator.audioSession)navigator.audioSession.type="playback";}catch(e){} speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w);u.lang="en-US";u.rate=.86;if(lookupVoices.length)u.voice=lookupVoices[(Number(state.voiceIndex)||0)%lookupVoices.length];speechSynthesis.speak(u);}
function statusFor(w){const mk=findKey(state.mastered,w.toLowerCase()),dk=findKey(state.debts,w.toLowerCase());if(mk)return {label:"已掌握",debt:0,peak:Number(state.highestDebt[mk]||0)};if(dk&&Number(state.debts[dk])>0)return {label:"学习中",debt:Number(state.debts[dk]),peak:Number(state.highestDebt[dk]||state.debts[dk])};return {label:"未学习",debt:1,peak:Number(state.highestDebt[w]||0)};}
function sourceFor(w){return (state.customWords||[]).some(x=>String(x).toLowerCase()===w.toLowerCase())?"自定义词库":"内置词库";}
function links(w){const yd=matchMedia&&matchMedia("(max-width:700px)").matches?"https://m.youdao.com/dict?le=eng&q="+encodeURIComponent(w):"https://dict.youdao.com/w/eng/"+encodeURIComponent(w);return '<div class="note lookupLinks"><a href="https://www.oxfordlearnersdictionaries.com/definition/english/'+encodeURIComponent(w.toLowerCase().replace(/\s+/g,"-"))+'" target="vocabLookup">📖 Oxford 英英</a><a href="'+yd+'" target="vocabLookup">📘 有道英中</a><a href="https://youglish.com/pronounce/'+encodeURIComponent(w)+'/english" target="vocabLookup">🎧 YouGlish 语境</a><a href="https://www.playphrase.me/#/search?q='+encodeURIComponent(w)+'" target="vocabLookup">🎬 PlayPhrase 影视</a><a href="https://www.rhymezone.com/r/rhyme.cgi?Word='+encodeURIComponent(w)+'&typeofrhyme=sim" target="vocabLookup">🔎 RhymeZone 近音</a></div>';}
function renderFound(w){const s=statusFor(w),nk=findKey(state.notes,w.toLowerCase()),note=nk?state.notes[nk]:"";$("lookupResult").innerHTML='<div class="lookupDetail"><div class="lookupStatusRow"><span>'+esc(s.label)+'</span><span>debt '+s.debt+'</span><span>peak '+s.peak+'</span><span>'+esc(sourceFor(w))+'</span></div><div class="lookupWord">'+esc(w)+'</div><button class="lookupSpeaker" id="lookupSpeak" type="button" aria-label="播放发音">🔊</button>'+pronunciationHtml(w)+links(w)+'<details class="wordNoteWrap noteDetails"'+(note?' open':'')+'><summary>笔记</summary><input id="lookupNote" class="wordNoteInput" type="text" placeholder="例如：容易和另一个词混；重音容易记错" value="'+esc(note)+'"></details></div>';$("lookupSpeak").onclick=()=>speak(w);$("lookupNote").onchange=$("lookupNote").onblur=()=>{const v=$("lookupNote").value.trim();const key=nk||w;if(v)state.notes[key]=v;else delete state.notes[key];save();};}
function validNew(q){return q&& !/[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]/.test(q) && !new Set(["a","an","the"]).has(q.toLowerCase());}
function renderMissing(q){const rem=removedWord(q);if(rem){$("lookupResult").innerHTML='<div class="lookupMissing"><b>'+esc(rem)+'</b><p>当前已从学习词库移除，学习历史和笔记仍保留。</p><button class="action" id="restoreLookup">恢复到词库</button></div>';$("restoreLookup").onclick=()=>{delete state.removedWords[rem];save();runLookup(rem);};return;}const ok=validNew(q);$("lookupResult").innerHTML='<div class="lookupMissing"><b>'+esc(q)+'</b><p>'+(ok?'不在当前词库中。':'不是可添加的英文词条。')+'</p>'+(ok?'<button class="action" id="addLookup">添加到词库</button>':'')+'</div>';if(ok)$("addLookup").onclick=()=>{state.customWords.push(q);save();runLookup(q);};}
function runLookup(raw){const q=String(raw||"").trim();if(!q)return;$("lookupInput").value=q;const w=canonicalWord(q);if(w)renderFound(w);else renderMissing(q);history.replaceState(null,"","lookup.html?word="+encodeURIComponent(q));}
$("lookupForm").onsubmit=e=>{e.preventDefault();runLookup($("lookupInput").value);};
loadPron();
