let lookupPronunciations={};
let lookupVoices=[];
const $=id=>document.getElementById(id);
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function findKey(obj,k){return Object.keys(obj||{}).find(x=>x.toLowerCase()===k)||null;}
function canonicalWord(q){const k=q.toLowerCase();return allWords().find(w=>w.toLowerCase()===k)||null;}
function removedWord(q){const k=q.toLowerCase();return Object.keys(state.removedWords||{}).find(w=>w.toLowerCase()===k)||null;}
function pronunciationHtml(w){const k=w.toLowerCase(),p=(state.customPronunciations&&state.customPronunciations[k])||lookupPronunciations[k];if(!p)return "";const a=[];if(p.uk)a.push('<span class="ipaChip ipaUk" title="UK" dir="ltr" lang="en">'+esc(p.uk)+'</span>');if(p.us)a.push('<span class="ipaChip ipaUs" title="US" dir="ltr" lang="en">'+esc(p.us)+'</span>');if(!a.length&&p.fallback)a.push('<span class="ipaChip ipaGeneric" title="IPA" dir="ltr" lang="en">'+esc(p.fallback)+'</span>');return a.length?'<div class="ipaLine">'+a.join('')+'</div>':"";}
async function loadPron(){try{const r=await fetch("data/pronunciations.json?v=3.29.0",{cache:"no-cache"});const j=await r.json();lookupPronunciations=j?.words||{};}catch(e){} const q=new URLSearchParams(location.search).get("word");if(q)runLookup(q);}
function preferredVoices(){const all=speechSynthesis.getVoices(),en=all.filter(v=>/^en([-_]|$)/i.test(v.lang||""));const novelty=/(bells?|boing|bubbles?|cellos?|good news|bad news|whisper|wobble|zarvox|trinoids?|organ|superstar|jester|bahh|deranged|hysterical|robot|novelty)/i;const p=en.filter(v=>!novelty.test(v.name||""));return p.length>=2?p:(en.length?en:all);}
function refreshVoices(){lookupVoices=preferredVoices();}
speechSynthesis.onvoiceschanged=refreshVoices;refreshVoices();
function speak(w){try{if("audioSession" in navigator&&navigator.audioSession)navigator.audioSession.type="playback";}catch(e){} speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w);u.lang="en-US";u.rate=.86;if(lookupVoices.length)u.voice=lookupVoices[(Number(state.voiceIndex)||0)%lookupVoices.length];speechSynthesis.speak(u);}
function statusFor(w){const mk=findKey(state.mastered,w.toLowerCase()),dk=findKey(state.debts,w.toLowerCase());if(mk)return {label:"已掌握",debt:0,peak:Number(state.highestDebt[mk]||0)};if(dk&&Number(state.debts[dk])>0)return {label:"学习中",debt:Number(state.debts[dk]),peak:Number(state.highestDebt[dk]||state.debts[dk])};return {label:"未学习",debt:1,peak:Number(state.highestDebt[w]||0)};}
function sourceFor(w){return (state.customWords||[]).some(x=>String(x).toLowerCase()===w.toLowerCase())?"自定义词库":"内置词库";}
function links(w){const yd=matchMedia&&matchMedia("(max-width:700px)").matches?"https://m.youdao.com/dict?le=eng&q="+encodeURIComponent(w):"https://dict.youdao.com/w/eng/"+encodeURIComponent(w);return '<div class="note lookupLinks"><a href="https://www.oxfordlearnersdictionaries.com/definition/english/'+encodeURIComponent(w.toLowerCase().replace(/\s+/g,"-"))+'" target="vocabLookup">📖 Oxford 英英</a><a href="'+yd+'" target="vocabLookup">📘 有道英中</a><a href="https://youglish.com/pronounce/'+encodeURIComponent(w)+'/english" target="vocabLookup">🎧 YouGlish 语境</a><a href="https://www.playphrase.me/#/search?q='+encodeURIComponent(w)+'" target="vocabLookup">🎬 PlayPhrase 影视</a><a href="https://www.rhymezone.com/r/rhyme.cgi?Word='+encodeURIComponent(w)+'&typeofrhyme=sim" target="vocabLookup">🔎 RhymeZone 近音</a></div>';}
function confusableLookupHtml(w){const a=getLinkedWords(w);return '<section class="confusableSection"><div class="confusableHead"><span>易混词</span><button class="confusableManageBtn" id="lookupManageConfusables" type="button">管理易混词</button></div>'+(a.length?'<div class="confusableList">'+a.map(x=>'<span class="confusableChip"><button class="confusableSpeak" type="button" data-ls="'+esc(x)+'">🔊</button><a href="lookup.html?word='+encodeURIComponent(x)+'">'+esc(x)+'</a></span>').join('')+'</div>':'<div class="confusableEmpty">还没有链接易混词</div>')+'<div class="confusableManager" id="lookupConfusableManager" hidden></div></section>';}
function renderLookupManager(w,msg=''){const box=$('lookupConfusableManager');if(!box)return;const a=getLinkedWords(w);box.innerHTML='<div class="confusableCount">'+a.length+' / 3</div>'+a.map(x=>'<div class="confusableManageRow"><span>'+esc(x)+'</span><div><button class="miniBtn" type="button" data-lms="'+esc(x)+'">🔊</button><button class="miniBtn confusableRemove" type="button" data-lu="'+esc(x)+'">移除</button></div></div>').join('')+'<div class="confusableAddRow"><input id="lookupConfusableInput" class="lookupInput" type="text" autocomplete="off" placeholder="输入易混词或词组"><button class="miniBtn" id="lookupConfusableAdd" type="button"'+(a.length>=3?' disabled':'')+'>添加</button></div>'+(a.length>=3?'<div class="confusableMessage">已达到 3 个上限，可先移除一个再添加。</div>':'')+(msg?'<div class="confusableMessage">'+esc(msg)+'</div>':'');box.querySelectorAll('[data-lms]').forEach(b=>b.onclick=()=>speak(b.dataset.lms));box.querySelectorAll('[data-lu]').forEach(b=>b.onclick=()=>{unlinkWords(w,b.dataset.lu);save();renderFound(w);setTimeout(()=>{const m=$('lookupConfusableManager');if(m){m.hidden=false;renderLookupManager(w);}},0);});const add=$('lookupConfusableAdd'),inp=$('lookupConfusableInput');if(add)add.onclick=()=>addLookupConfusable(w,inp.value);if(inp)inp.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();addLookupConfusable(w,inp.value);}};}
function addLookupConfusable(w,raw){const q=String(raw||'').trim();if(!q)return;if(q.toLowerCase()===w.toLowerCase()){renderLookupManager(w,'不能把单词和自己链接。');return;}let t=findWordCaseInsensitive(q,true);if(t&&isRemovedWord(t)){renderLookupManager(w,t+' 当前已移除，请先恢复后再链接。');return;}if(!t){if(!validNew(q)){renderLookupManager(w,'请输入有效的英文单词或词组。');return;}state.customWords.push(q);t=q;}const r=linkWords(w,t);if(!r.ok){renderLookupManager(w,r.reason==='target-full'?t+' 已经链接了 3 个易混词，请先移除一个。':'当前词已经达到 3 个易混词上限。');return;}save();renderFound(w);setTimeout(()=>{const m=$('lookupConfusableManager');if(m){m.hidden=false;renderLookupManager(w);}},0);}
function renderFound(w){const s=statusFor(w),nk=findKey(state.notes,w.toLowerCase()),note=nk?state.notes[nk]:"";$("lookupResult").innerHTML='<div class="lookupDetail"><div class="lookupStatusRow"><span>'+esc(s.label)+'</span><span>debt '+s.debt+'</span><span>peak '+s.peak+'</span><span>'+esc(sourceFor(w))+'</span></div><div class="lookupWord">'+esc(w)+'</div><button class="lookupSpeaker" id="lookupSpeak" type="button" aria-label="播放发音">🔊</button>'+pronunciationHtml(w)+links(w)+confusableLookupHtml(w)+'<details class="wordNoteWrap noteDetails"'+(note?' open':'')+'><summary>笔记</summary><input id="lookupNote" class="wordNoteInput" type="text" placeholder="例如：容易和另一个词混；重音容易记错" value="'+esc(note)+'"></details></div>';$("lookupSpeak").onclick=()=>speak(w);document.querySelectorAll('[data-ls]').forEach(b=>b.onclick=()=>speak(b.dataset.ls));$('lookupManageConfusables').onclick=()=>{const box=$('lookupConfusableManager');box.hidden=!box.hidden;if(!box.hidden)renderLookupManager(w);};$("lookupNote").onchange=$("lookupNote").onblur=()=>{const v=$("lookupNote").value.trim();const key=nk||w;if(v)state.notes[key]=v;else delete state.notes[key];save();};}
function validNew(q){return q&& !/[\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]/.test(q) && !new Set(["a","an","the"]).has(q.toLowerCase());}
function renderMissing(q){const rem=removedWord(q);if(rem){$("lookupResult").innerHTML='<div class="lookupMissing"><b>'+esc(rem)+'</b><p>当前已从学习词库移除，学习历史和笔记仍保留。</p><button class="action" id="restoreLookup">恢复到词库</button></div>';$("restoreLookup").onclick=()=>{delete state.removedWords[rem];save();runLookup(rem);};return;}const ok=validNew(q);$("lookupResult").innerHTML='<div class="lookupMissing"><b>'+esc(q)+'</b><p>'+(ok?'不在当前词库中。':'不是可添加的英文词条。')+'</p>'+(ok?'<button class="action" id="addLookup">添加到词库</button>':'')+'</div>';if(ok)$("addLookup").onclick=()=>{state.customWords.push(q);save();runLookup(q);};}
function runLookup(raw){const q=String(raw||"").trim();if(!q)return;$("lookupInput").value=q;const w=canonicalWord(q);if(w)renderFound(w);else renderMissing(q);history.replaceState(null,"","lookup.html?word="+encodeURIComponent(q));}
$("lookupSubmit").onclick=()=>runLookup($("lookupInput").value);
$("lookupForm").onsubmit=e=>{e.preventDefault();runLookup($("lookupInput").value);};
loadPron();
