const TAG_KEY="audio_vocab_sprint_universal_v3";
let tagState=JSON.parse(localStorage.getItem(TAG_KEY)||"null")||{};
tagState.tags=(tagState.tags&&typeof tagState.tags==="object"&&!Array.isArray(tagState.tags))?tagState.tags:{};
tagState.wordTags=(tagState.wordTags&&typeof tagState.wordTags==="object"&&!Array.isArray(tagState.wordTags))?tagState.wordTags:{};
tagState.customWords=Array.isArray(tagState.customWords)?tagState.customWords:[];tagState.removedWords=tagState.removedWords||{};
const TBASE=window.BASE_WORDS||[];const $=id=>document.getElementById(id);const h=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function saveTags(){localStorage.setItem(TAG_KEY,JSON.stringify(tagState));}
function tags(){return Object.entries(tagState.tags).map(([id,t])=>({id,name:String(t?.name||"").trim(),color:String(t?.color||"#8b7cf6")})).filter(t=>t.name).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN'));}
function words(){const removed=new Set(Object.keys(tagState.removedWords||{}).map(x=>x.toLowerCase())),seen=new Set(),out=[];for(const raw of TBASE.concat(tagState.customWords)){const w=String(raw||'').trim(),k=w.toLowerCase();if(w&&!seen.has(k)&&!removed.has(k)){seen.add(k);out.push(w);}}return out;}
function count(id){let n=0;for(const ids of Object.values(tagState.wordTags||{}))if(Array.isArray(ids)&&ids.includes(id))n++;return n;}
function selectedTag(){return new URLSearchParams(location.search).get('tag')||'';}
function render(){const all=tags(),sel=selectedTag();$('tagCount').textContent=all.length;$('tagGrid').innerHTML=all.length?all.map(t=>'<div class="tagLibraryCard '+(sel===t.id?'is-selected':'')+'" data-open="'+h(t.id)+'" role="button" tabindex="0"><span class="tagColorDot" style="--tag-color:'+h(t.color)+'"></span><span><b>'+h(t.name)+'</b><small>'+count(t.id)+' 个单词</small></span><span class="tagCardActions"><button type="button" class="tagEditButton" data-edit="'+h(t.id)+'">编辑</button></span></div>').join(''):'<div class="tagEmptyPanel">还没有标签。创建第一个标签后，就可以给任意单词添加。</div>';const openCard=b=>{const u=new URL(location.href);u.searchParams.set('tag',b.dataset.open);history.replaceState(null,'',u);render();};$('tagGrid').querySelectorAll('[data-open]').forEach(b=>{b.onclick=e=>{const edit=e.target.closest('[data-edit]');if(edit){e.stopPropagation();openEditor(edit.dataset.edit);return;}openCard(b);};b.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('[data-edit]')){e.preventDefault();openCard(b);}};});renderWords(sel);}
function renderWords(id){const root=$('tagWords');if(!id||!tagState.tags[id]){root.innerHTML='<div class="tagBrowseEmpty">选择一个标签查看其中的单词。</div>';return;}const t=tagState.tags[id],arr=words().filter(w=>(tagState.wordTags[w.toLowerCase()]||[]).includes(id));root.innerHTML='<div class="tagBrowseHead"><span class="wordTagChip" style="--tag-color:'+h(t.color)+'">'+h(t.name)+'</span><b>'+arr.length+' 个单词</b></div>'+(arr.length?'<div class="tagWordList">'+arr.map(w=>'<a href="lookup.html?word='+encodeURIComponent(w)+'&v=3.33.2">'+h(w)+'</a>').join('')+'</div>':'<div class="tagBrowseEmpty">这个标签下还没有单词。</div>');}
const TAG_COLORS=['#e39a88','#d67a64','#cb8b5b','#e7ab64','#f6c96c','#f5e06f','#d6d970','#acbe6c','#89d5a6','#94d0d7','#7bb9ca','#7a8fb5','#988dd4','#d1a5b1','#ac8891'];
function openEditor(existing){
  const old=$('tagEditorBackdrop');if(old)old.remove();
  const t=existing?tagState.tags[existing]:null,wrap=document.createElement('div');
  let chosen=(t&&TAG_COLORS.includes(String(t.color||'').toLowerCase()))?String(t.color).toLowerCase():TAG_COLORS[0];
  wrap.id='tagEditorBackdrop';wrap.className='ipaEditorBackdrop';
  const palette=TAG_COLORS.map(c=>'<button class="tagPaletteColor'+(c===chosen?' is-selected':'')+'" type="button" data-color="'+c+'" style="--tag-color:'+c+'" aria-label="选择颜色 '+c+'"></button>').join('');
  wrap.innerHTML='<div class="ipaEditor"><div class="ipaEditorHead"><b>'+(t?'编辑标签':'新建标签')+'</b><button class="ipaEditorClose">×</button></div><div class="ipaEditorRow"><label>名称</label><input class="ipaEditorInput" id="tagName" maxlength="20" value="'+h(t?.name||'')+'" placeholder="例如：医学"></div><div class="ipaEditorRow tagPaletteRow"><label>颜色</label><div class="tagPalette" id="tagPalette">'+palette+'</div></div><div class="tagEditorMsg" id="tagEditorMsg"></div><div class="ipaEditorActions">'+(t?'<button class="tagDeleteBtn" id="tagDelete">删除标签</button>':'')+'<button class="ipaSave" id="tagSave">保存</button></div></div>';
  document.body.appendChild(wrap);
  const close=()=>wrap.remove();wrap.querySelector('.ipaEditorClose').onclick=close;wrap.onclick=e=>{if(e.target===wrap)close();};
  wrap.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{chosen=b.dataset.color;wrap.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('is-selected',x===b));});
  $('tagSave').onclick=()=>{const name=$('tagName').value.trim();if(!name){$('tagEditorMsg').textContent='请输入标签名称。';return;}if(tags().some(x=>x.id!==existing&&x.name.toLowerCase()===name.toLowerCase())){$('tagEditorMsg').textContent='已经有同名标签。';return;}if(existing)tagState.tags[existing]={name,color:chosen};else{const id='tag_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,7);tagState.tags[id]={name,color:chosen};}saveTags();close();render();};
  if(t)$('tagDelete').onclick=()=>{if($('tagDelete').dataset.confirm!=='1'){$('tagDelete').dataset.confirm='1';$('tagDelete').textContent='再次点击确认删除';return;}delete tagState.tags[existing];for(const [w,ids] of Object.entries(tagState.wordTags)){const n=(Array.isArray(ids)?ids:[]).filter(x=>x!==existing);if(n.length)tagState.wordTags[w]=n;else delete tagState.wordTags[w];}saveTags();close();const u=new URL(location.href);u.searchParams.delete('tag');history.replaceState(null,'',u);render();};
}
$('newTagBtn').onclick=()=>openEditor(null);render();
