import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,readdirSync} from 'node:fs';import {resolve,dirname,join} from 'node:path';import {fileURLToPath} from 'node:url';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');const read=p=>readFileSync(join(root,p),'utf8');
test('all HTML pages use one shared refresh runtime',()=>{for(const f of readdirSync(root).filter(x=>x.endsWith('.html'))){const s=read(f);assert.match(s,/js\/runtime\.js\?v=/,f);assert.doesNotMatch(s,/CURRENT_BUILD/,f);}});
test('persisted state key has one definition',()=>{const defs=[];for(const f of readdirSync(join(root,'js')).filter(x=>x.endsWith('.js'))){if(/(?:const|let|var)\s+[A-Z_]*STATE[A-Z_]*\s*=\s*['\"]audio_vocab_sprint_universal_v3['\"]/.test(read('js/'+f)))defs.push(f);}assert.deepEqual(defs,['state-core.js']);});
test('state consumers use shared state-core',()=>{for(const f of ['index.html','active.html','mastered.html','confusable.html','removed.html','notes.html','history.html','tags.html','lookup.html'])assert.match(read(f),/js\/state-core\.js\?v=/,f);});
test('version mutation is automated',()=>{const pkg=JSON.parse(read('package.json'));assert.equal(pkg.scripts['version:set'],'node scripts/set-version.mjs');});

test('app shell no longer owns search or import implementation',()=>{const app=read('js/app.js');assert.doesNotMatch(app,/function homeSearchWords/);assert.doesNotMatch(app,/function parseCsvVocabulary/);assert.match(read('js/home-search.js'),/function homeSearchWords/);assert.match(read('js/data-io.js'),/function parseCsvVocabulary/);});
test('app shell delegates high-risk UI responsibilities',()=>{const app=read('js/app.js');assert.ok(app.split('\n').length<600,'app.js should stay below 600 lines');assert.doesNotMatch(app,/function openPronunciationEditor/);assert.doesNotMatch(app,/function openConfusableManager/);assert.doesNotMatch(app,/function dissolveCurrentWord/);assert.match(read('js/pronunciation-ui.js'),/function openPronunciationEditor/);assert.match(read('js/word-metadata-ui.js'),/function openConfusableManager/);assert.match(read('js/judgment-feedback.js'),/function dissolveCurrentWord/);});
test('judgment feedback module does not mutate learning maps',()=>{const s=read('js/judgment-feedback.js');for(const field of ['state.debts','state.mastered','state.seen','state.dailyStats'])assert.doesNotMatch(s,new RegExp(field.replace('.','\\.')),field);});
test('main script order exposes boundaries before app shell',()=>{const html=read('index.html');const order=['js/state-core.js','js/storage.js','js/scheduler.js','js/judgment-feedback.js','js/external-links.js','js/pronunciation-ui.js','js/word-metadata-ui.js','js/app.js','js/home-search.js','js/data-io.js','js/github-sync.js'];let last=-1;for(const item of order){const at=html.indexOf(item);assert.ok(at>last,`${item} script order`);last=at;}});
test('version tool usage text is version-agnostic',()=>{assert.match(read('scripts/set-version.mjs'),/-- x\.y\.z/);});

test('home confusable playback reuses the existing pause preference and current voice',()=>{const ui=read('js/word-metadata-ui.js');assert.match(ui,/audio_vocab_sprint_confusable_pause_ms/);assert.match(ui,/\[state\.current,\.\.\.getLinkedWords\(state\.current\)\]/);assert.match(ui,/voice=selectedVoice\(\)/);assert.match(ui,/setTimeout\(\(\)=>next\(i\+1\),pause\)/);assert.doesNotMatch(ui,/localStorage\.setItem\(CONFUSABLE_PAUSE_KEY/);});
